### ISSUE TITLE
react\react.js does not export default

### ISSUE THREAD

**Issue by egoist** [rollup/rollup-plugin-npm#10]
I have React installed in `node_modules` and import it in `./src/main.js`, with such configs:

```javascript
{
  entry: './src/main',
  dest: './build/bundle.rollup.js',
	plugins: [
      npm({
        main: true
      }),
      commonjs({
        include: 'node_modules/**'
      }),
      babel({
        exclude: 'node_modules/**'
      })
  ],
  format: 'iife'
}

```

But it ran into some issue:

```bash
Module *\react\react.js does not export default (imported by *\src\main.js)
```

Without `rollup-plugin-npm` it works but sure it does not include React in the Rollup bundle.

**Comment by Rich-Harris** [comment]
That's odd. It works for me in this simple example: https://gist.github.com/Rich-Harris/cd0c293f5263b2450412. (Clone it, `npm i`, then `npm run build` – it will open a test page that logs the value of `React`.) Can you share your repo?

Strictly speaking, your code should probably say

```js
import * as React from 'react';
```

rather than

```js
import React from 'react';
```

since React itself is just a namespace.

**Comment by egoist** [comment]
thx, this should work.

**Comment by atombender** [comment]
Getting the same error here. And using `import * as React` shouldn't really be necessary. We're investigating migrating from Browserify, which is quite happy to import React like this. In particular, we use the idiom:

    import React, {PropTypes} from 'react';

**Comment by atombender** [comment]
I'm wondering if this related:

```
Module /tmp/foo/node_modules/react-router/lib/index.js does not export Route (imported by /tmp/foo/app/components/Root.react.jsx)
```

That particular module uses [this way](https://gist.github.com/atombender/d1bf3e104b89e4ecd49d) of exporting stuff. Works with Browserify, though.

**Comment by atombender** [comment]
Looks like using `rollbar-plugin-commonjs` instead of this package solves these issues.

**Comment by dtothefp** [comment]
@atombender @Rich-Harris I'm confused about this error, I get it when using the `babel` plugin along with the `node-resolve` and `commonjs` rollup plugins. 

If I build my code allowing all `node_modules` `include`ed in the `commonjs` plugin, I get errors with `babel-runtime` helpers. 

```
Uncaught TypeError: _createClass is not a function
```

because it is trying to call a `['default']` key `var _createClass = require$$9$1['default'];`, where when it is assigned to the variable `require$$9$1` it has already accessed the function from the default key

```js
//this ternary check is true
var require$$9$1 = (createClass && typeof createClass === 'object' && 'default' in createClass ? createClass['default'] : createClass);
```

When I exclude the `babel-runtime` helpers from the commonjs plugin I get a compilation error

```
[Error: Module /Users/davidfox-powell/dev/mobile-donate/node_modules/babel-runtime/helpers/interop-require-wildcard.js does not export default
```

https://github.com/rollup/rollup/blob/157ba12cedf62f8833bbcbb90ba55ca4f18631fe/src/Module.js#L620

I have no idea why this is happening, and am curious if it is a bug or I am just not including/excluding properly?

**Comment by Hikariii** [comment]
Having the same kind of issue:

In my rollup config I have the following:
```javascript
{
    globals: { "underscore": "require('underscore')"},
    external: ['underscore']
}
```


My iife bundle function is called like:
```javascript
(function (_) {
'use strict';

var ___default = _['default'];

///all the code

}(require('underscore')));
```

But inside the code ```___default``` is undefined.
Can't I force rollupJS to just assign underscore like this:
```
_= 'default' in _? _['default'] : _;
```

**Comment by Hikariii** [comment]
Just added ```interop: false``` to the rollup config and recompiled.
This solved my problem.

**Comment by dtothefp** [comment]
hey @Hikariii not sure about underscore, but to get lodash working I used common-js plugin. Maybe this helps `¯\_(ツ)_/¯`

```js
       nodeResolve({
      extensions: ['.js'],
      main: true,
      browser: true,
      preferBuiltins: false
    }),
    commonjs({
      namedExports: {
        lodash: [
          'assign',
          'keys',
          'max',
          'set',
          'values'
        ]
      },
      include: [
        'node_modules/**/*.js'
      ],
      exclude: [
        es6Glob
      ]
    }),
```

**Comment by wan54** [comment]
Any updates on this? Got the same issue with React.

`var React__default = React['default'];`
// React['default'] is undefined

**Comment by wan54** [comment]
We were using 0.56.5. Upgraded to 0.62.0 fixed the issue.
